version: 0.1
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing Dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping Deployment packages..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g GetProduct_package.zip lambda_function.py.y
  
  post_build:
    commands:
      - echo "Updating lamda Function..."
      - aws lambda update-function-code --function-name pyGetProductList --zip-file fileb://GetProduct_package.zip
      - echo "Done !!!"